# Generated by Django 3.2.13 on 2022-05-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('uid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('dob', models.DateField()),
                ('times', models.TimeField()),
                ('dttime', models.DateTimeField()),
                ('img', models.ImageField(upload_to='pics')),
                ('address', models.TextField()),
            ],
        ),
    ]
