# Generated by Django 3.2.13 on 2022-05-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=30)),
                ('fees', models.IntegerField()),
                ('trainer', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
